### ISSUE TITLE
 New bloom release of marti_messages to ROS 2 Rolling

### ISSUE THREAD

**Issue by clalancette** [swri-robotics/marti_messages#112]
We've recently made some changes to ROS 2 Rolling that requires a new bloom release of this message package.  This will fix the failing package build on Rolling that you can see in https://build.ros2.org/view/Rbin_uF64/job/Rbin_uF64__marti_can_msgs__ubuntu_focal_amd64__binary/76/ (amongst others) .  Note that we only require a bloom release; a new source release should not be necessary.  To re-release this package the following steps should be performed:

```
$ sudo apt-get update
$ sudo apt-get install python3-bloom
# Ensure that the bloom-version you are using is 0.10.3 by running 'bloom-release --version'
$ bloom-release --track rolling --rosdistro rolling marti_messages
```

Please let me know if you have any questions about this.  Thank you.

**Comment by clalancette** [comment]
Friendly ping here; can someone perform the bloom-release to unstick this package?  Thanks.

**Comment by matt-attack** [comment]
@daniel-dsouza or @danthony06  do you think you can do this? I can try and figure it out if needed.

**Comment by danthony06** [comment]
I haven't bloomed a package before. I can take a look at it and try to
figure it out, unless @daniel-dsouza has time to do it.

**Comment by clalancette** [comment]
I am more than willing to do it, but I would have to be given write access to https://github.com/swri-robotics-gbp/marti_messages-release.git .  But either way works for me.  Thanks!

**Comment by danthony06** [comment]
@preed can you give me write access?

**Comment by pjreed** [comment]
Done, although probably @daniel-dsouza should be the person to give out access and I don't know if I should have access to it any more. :-)

**Comment by danthony06** [comment]
I'm starting to work on it now.

**Comment by danthony06** [comment]
I should bloom out of the dashing-devel branch, correct?

**Comment by pjreed** [comment]
Yes; since it's been bloomed into rolling before, it should use `dashing-devel` by default.

**Comment by danthony06** [comment]
I'm getting this error when I try to bloom. Any thoughts on what's going on?
```
~/ros2_rolling/src/marti_messages (dashing-devel) $ bloom-release --track rolling --rosdistro rolling marti_messages
ROS Distro index file associate with commit 'f0dd791198158569c5fa5f4ab03d560d052921db'
New ROS Distro index url: 'https://raw.githubusercontent.com/ros/rosdistro/f0dd791198158569c5fa5f4ab03d560d052921db/index-v4.yaml'
==> Fetching 'marti_messages' repository from 'https://github.com/ros2-gbp/marti_messages-release.git'
Cloning into '/tmp/tmpxypkd2og'...
remote: Enumerating objects: 11959, done.
remote: Counting objects: 100% (11959/11959), done.
remote: Compressing objects: 100% (5273/5273), done.
remote: Total 11959 (delta 6236), reused 11890 (delta 6168), pack-reused 0
Receiving objects: 100% (11959/11959), 1.78 MiB | 8.50 MiB/s, done.
Resolving deltas: 100% (6236/6236), done.
==> Setting release repository remote url to 'git@github.com:swri-robotics-gbp/marti_messages-release.git'
==> git remote set-url origin git@github.com:swri-robotics-gbp/marti_messages-release.git
==> Testing for push permission on release repository
==> git remote -v
origin  git@github.com:swri-robotics-gbp/marti_messages-release.git (fetch)
origin  git@github.com:swri-robotics-gbp/marti_messages-release.git (push)
==> git push --dry-run
To github.com:swri-robotics-gbp/marti_messages-release.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:swri-robotics-gbp/marti_messages-release.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Cannot push to remote release repository.
Hint: If you just typed in your username/password and you have two-factor authentication,see:
  http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization
  ```

**Comment by clalancette** [comment]
Hm.  That may be because https://github.com/ros2-gbp/marti_messages-release.git and https://github.com/swri-robotics-gbp/marti_messages-release.git are out-of-sync with each other.  Honestly, this is an unusual configuration to have, where the `ros2-gbp` configuration points to a separate repository.  Let me check in with some people and see if we can figure this out.

**Comment by nuclearsandwich** [comment]
In order to support the automation which powers the Rolling release tools we need the release repositories to be push-able by our automation and by default all release repositories were cloned to the [ros2-gbp](https://github.com/ros2-gbp) organization.

My advice would be to switch to the ros2-gbp repository for future releases in all distributions. I can help with updating the ros2-gbp repository with all contents from the current release repository so that future releases to all ROS 2 distributions can be made from there.

I can also make sure that the entire maintenance team has the necessary access to release to the ros2-gbp repository.

If the team would like to continue using the current release repository for stable ROS 2 distributions that is also doable but will require switching between the ros2-gbp and swri-robotics-gbp release repositories once each stable distribution has been created from Rolling.

If the team would prefer not to provide packages in the Rolling release at all we can also remove the packages from the Rolling distribution and then your team would use the same process used previously to release packages into a new distribution for the first time.

My _strong_ recommendation is to adopt the ros2-gbp repository as the primary one for all ROS 2 distributions and if that's the consensus I'm happy to do the grunt work of re-synchronizing it with the repository used for stable distributions and prepare it for your team's first release into Rolling. To get your team access I just need to know the GitHub usernames of those who would need to be added.

**Comment by danthony06** [comment]
We're talking it over. We're leaning towards the ros2-gbp repo, but want to make sure this isn't going to cause issues.

**Comment by danthony06** [comment]
@nuclearsandwich We're going to go with your recommendation, and switch to the ros2-gbp repository. Can you add myself and @daniel-dsouza to the list of Github usernames?

**Comment by nuclearsandwich** [comment]
> Can you add myself and @daniel-dsouza to the list of Github usernames?

Sounds good. I'm on it!

**Comment by nuclearsandwich** [comment]
@daniel-dsouza @danthony06 you should have both received invitations to the ros2-gbp repository. I've also updated the repository with all branches, refs, and tracks.yaml changes from that have occurred since the repository was first created. Once you accept the invitations you should be able to create new releases to rolling. I also opened https://github.com/ros/rosdistro/pull/29067 which updates the release repositories for Dashing and Foxy so that they all use the same release repository.

A quick glance suggests that you might be using the same repository for ROS 1 distributions as well. In which case it may make sense to update https://github.com/ros/rosdistro/pull/29067 to include active ROS 1 distributions however since there is no Rolling infrastructure there you could continue to use the swri-robotics-gbp repository for ROS 1 with no adverse technical effects.

Thanks for _rolling_ with us on this one!

**Comment by danthony06** [comment]
Got it. I'll try to work on it this weekend.

**Comment by danthony06** [comment]
@nuclearsandwich So that we can get you going on this, let's release Dashing and Foxy, and then we can switch our ROS 1 repos over later.

**Comment by nuclearsandwich** [comment]
The marti_messages packages still need a re-release in Rolling to fix the typesupport dependencies. I have proposed that we temporarily drop marti_messages from the Rolling releases until the issue is resolved https://github.com/ros/rosdistro/pull/30320

**Comment by danthony06** [comment]
How do I trigger the release?

**Comment by pjreed** [comment]
Normally that should be as easy as running `bloom-release --track rolling --rosdistro rolling marti_messages`, although digging back into the history [here](https://github.com/swri-robotics/marti_messages/issues/112), it looks like there were some issues synchronizing between the ros2-gbp and swri-robotics-gbp repositories.  Did that ever get cleaned up?  You might just try running the bloom command again to see what happens, although it might need a little more work.

**Comment by nuclearsandwich** [comment]
I believe I've integrated all history from the swri-robotics-gbp repositories into the ros2-gbp ones. So as long as the releaser has access to the ros2-gbp repository we should be good to go.

**Comment by danthony06** [comment]
@nuclearsandwich I just tried to bloom this, and got an error. I've attached my console output.
[release.log](https://github.com/swri-robotics/marti_messages/files/7100821/release.log)

**Comment by danthony06** [comment]
Not sure what's going on here, I'm a little stumped.

**Comment by danthony06** [comment]
If this is somehow caused by us using our own release repos, instead of switching over to the new infrastructure, I'm also happy to make that switch completely now.

**Comment by danthony06** [comment]
@clalancette or @nuclearsandwich I'm still trying to figure this out, and it's causing us issues. Is there a good way to switch to the ros2-gbp repos, and get this relesed for everything from those repos?

**Comment by danthony06** [comment]
Done, through here: https://github.com/ros2-gbp/marti_messages-release/pull/2
